### ISSUE TITLE
Curiosity about the impact of the "workload_size" option choice on the experimental environment.

### ISSUE THREAD

**Issue by jeongeunKim-art** [addb-swstarlab/TMPTune#1]
Hello,

First, I would like to express my gratitude for your excellent research. 

I have a question regarding the Bounce project. I am curious about the impact of the "workload_size" option on the experimental environment. In the main.py file, this option is categorized into "tiny", "small", and "large", and I would like to understand the specific effects of each selection on experiment performance, execution time, and resource usage.

**Comment by JIEUN-12** [comment]
Thank you for your interest!

The workload_size sets a scale for HiBench to load data, and the tiny, small, and large options represent their defined data size.
If you want to load large amounts of data, there are more options such as huge and bigdata.

In summary, the workload_size option only affects the benchmark duration ranges performed.
