### ISSUE TITLE
Clarification Needed on --workload_size Parameter Criteria

### ISSUE THREAD

**Issue by HwanheeKim813** [addb-swstarlab/TMPTune#2]
In the main.py file, the --workload_size parameter allows for specifying the size of the workload with the following choices: tiny, small, large, huge, gigantic. However, the criteria or definitions for each of these workload sizes are not documented. What are the specific criteria or metrics that define each of these workload sizes (tiny, small, large, huge, gigantic)? For example, does each size correspond to a specific number of records, the size of data files, or some other metric?

**Comment by JIEUN-12** [comment]
Hi, thank you for your question. The `--workload_size` parameter in the main.py file refers to the default data sizes provided by the HiBench benchmark suite. The sizes (tiny, small, large, huge, gigantic) correspond to predefined datasets that are commonly used for benchmarking purposes. 

For detailed information about the specific criteria for each size, such as the number of records or the size of data files, you can refer to the official HiBench documentation [here](https://github.com/Intel-bigdata/HiBench).
