### ISSUE TITLE
Questions about the dataset and a model function

### ISSUE THREAD

**Issue by eunji66-kim** [addb-swstarlab/TMPTune#3]
Hello authors,

First of all, thank you for offering your codes.

I have some questions related your codes.

1. There is one csv data in the data folder. How did you get this data and is there any additional data to train and test the proposed method?
2. In README file, you are saying that "it is able to select an optimal configuration with reliable performance by reducing the impact of noise." I wonder which part is responsible for this.

Thanks.

**Comment by JIEUN-12** [comment]
Hello,

Thank you for your interest in our codes and for reaching out with your questions.

The CSV file in the data folder contains parameter information, including the types of parameters and their valid ranges. This information is necessary for tuning the parameters. As the method assumes a cold-start scenario, there is no additional training or testing dataset provided.

Currently, this code is part of a submission to an upcoming paper. For further details and discussions regarding this work, we kindly ask you to wait for the publication of the paper.

Thank you for your understanding, and feel free to reach out if you have any other questions.
