### ISSUE TITLE
About noise

### ISSUE THREAD

**Issue by kkIIun** [addb-swstarlab/TMPTune#4]
Hello,

Thank you for sharing your code and making it accessible. I truly appreciate your efforts.

I’m a bit unclear about the use of noise in your implementation. Could you please explain what “noise” and “noise_mode” refer to and how they are used?

Thank you for your time and assistance.

**Comment by JIEUN-12** [comment]
Thank you for your interest.

`noise_mode` is a variable that was used during the model ideation process and will be deleted in a later version. You can ignore it and run, where this parser will be set to a default value.

We will also be adding a concept for noise in the future.
